default_language_version:
  python: python3.11

repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: check-symlinks
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: trailing-whitespace

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    - id: codespell
      name: codespell
      # description: Checks for common misspellings in text files.
      # entry: codespell --ignore-words ignore-spelling-words.txt readme.md code.py
      # language: python
      # types: [text]
      args: [-I, .codespellignore]
      exclude: >
                (?x)^(
                    .*\.json|
                    .*\.lock|
                    .*\.pyc|
                    \.tox
                )$

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black

-   repo: https://github.com/python-poetry/poetry
    rev: '1.5.0'
    hooks:
    - id: poetry-check
    # - id: poetry-lock
